@url = http://localhost:3011

### base route
{{url}}

### jobs
{{url}}/jobs

### delete a job
DELETE {{url}}/jobs/3 

### save an edited job
PATCH {{url}}/job
content-type: application/json
 
{
	"id": 1,
	"title": "ttt",
	"company": "ccc",
	"url": "uuu",
	"description": "ddd",
	"skillList": "sss",
	"todo": "ttt"
}